/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { BasicError } from '../schemas/BasicError';

export type ForbiddenResponse = BasicError;
