/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { ValidationError } from '../schemas/ValidationError';

export type ValidationFailedResponse = ValidationError;
