/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { UserArrayRequestBody } from '../requestBodies/UserArrayRequestBody';
import { fetcher, FetcherOptions } from './fetcher';

export type CreateUsersWithArrayInputResponse = unknown;

export type CreateUsersWithArrayInputError = unknown;

export interface CreateUsersWithArrayInputProps
	extends Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function createUsersWithArrayInput(
	props: CreateUsersWithArrayInputProps,
): Promise<CreateUsersWithArrayInputResponse> {
	const { ...rest } = props;

	return fetcher<CreateUsersWithArrayInputResponse, unknown, unknown>({
		url: `/user/createWithArray`,
		method: 'POST',
		...rest,
	});
}

/**
 *
 */
export function useCreateUsersWithArrayInputMutation(
	props: CreateUsersWithArrayInputProps,
	options: Omit<
		UseMutationOptions<CreateUsersWithArrayInputResponse, CreateUsersWithArrayInputError>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<CreateUsersWithArrayInputResponse, CreateUsersWithArrayInputError>(
		() => createUsersWithArrayInput(props),
		options,
	);
}
