/* This is a sample header */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { UserArrayRequestBody } from '../requestBodies/UserArrayRequestBody';
import { fetcher, FetcherOptions } from './fetcher';

export type CreateUsersWithListInputRequestBody = UserArrayRequestBody;

export type CreateUsersWithListInputOkResponse = unknown;

export type CreateUsersWithListInputErrorResponse = unknown;

export interface CreateUsersWithListInputProps
	extends Omit<FetcherOptions<unknown, CreateUsersWithListInputRequestBody>, 'url'> {
	body: CreateUsersWithListInputRequestBody;
}

export function createUsersWithListInput(
	props: CreateUsersWithListInputProps,
): Promise<CreateUsersWithListInputOkResponse> {
	return fetcher<CreateUsersWithListInputOkResponse, unknown, CreateUsersWithListInputRequestBody>({
		url: `/user/createWithList`,
		method: 'POST',
		...props,
	});
}

export type CreateUsersWithListInputMutationProps<T extends keyof CreateUsersWithListInputProps> =
	Omit<CreateUsersWithListInputProps, T> & Partial<Pick<CreateUsersWithListInputProps, T>>;

/**
 *
 */
export function useCreateUsersWithListInputMutation<T extends keyof CreateUsersWithListInputProps>(
	props: Pick<Partial<CreateUsersWithListInputProps>, T>,
	options?: Omit<
		UseMutationOptions<
			CreateUsersWithListInputOkResponse,
			CreateUsersWithListInputErrorResponse,
			CreateUsersWithListInputMutationProps<T>
		>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<
		CreateUsersWithListInputOkResponse,
		CreateUsersWithListInputErrorResponse,
		CreateUsersWithListInputMutationProps<T>
	>(
		(mutateProps: CreateUsersWithListInputMutationProps<T>) =>
			createUsersWithListInput({ ...props, ...mutateProps } as CreateUsersWithListInputProps),
		options,
	);
}
