/* This is a sample header */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import { fetcher, FetcherOptions } from './fetcher';

export interface DeleteUserMutationPathParams {
	username: string;
}

export type DeleteUserOkResponse = unknown;

export type DeleteUserErrorResponse = unknown;

export interface DeleteUserProps
	extends DeleteUserMutationPathParams,
		Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function deleteUser(props: DeleteUserProps): Promise<DeleteUserOkResponse> {
	const { username, ...rest } = props;

	return fetcher<DeleteUserOkResponse, unknown, unknown>({
		url: `/user/${username}`,
		method: 'DELETE',
		...rest,
	});
}

/**
 * This can only be done by the logged in user.
 */
export function useDeleteUserMutation(
	props: DeleteUserProps,
	options?: Omit<
		UseMutationOptions<DeleteUserOkResponse, DeleteUserErrorResponse>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<DeleteUserOkResponse, DeleteUserErrorResponse>(
		() => deleteUser(props),
		options,
	);
}
