/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import { fetcher, FetcherOptions } from './fetcher';

export interface UseDeleteUserMutationPathParams {
	username: string;
}

export type DeleteUserResponse = unknown;

export type DeleteUserError = unknown;

export interface DeleteUserProps
	extends UseDeleteUserMutationPathParams,
		Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function deleteUser(props: DeleteUserProps): Promise<DeleteUserResponse> {
	const { username, ...rest } = props;

	return fetcher<DeleteUserResponse, unknown, unknown>({
		url: `/user/${username}`,
		method: 'DELETE',
		...rest,
	});
}

/**
 * This can only be done by the logged in user.
 */
export function useDeleteUserMutation(
	props: DeleteUserProps,
	options: Omit<
		UseMutationOptions<DeleteUserResponse, DeleteUserError>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<DeleteUserResponse, DeleteUserError>(() => deleteUser(props), options);
}
