/* This is a sample header */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import { fetcher, FetcherOptions } from './fetcher';

export interface DeleteOrderMutationPathParams {
	/**
	 * @format int64
	 */
	orderId: number;
}

export type DeleteOrderOkResponse = unknown;

export type DeleteOrderErrorResponse = unknown;

export interface DeleteOrderProps
	extends DeleteOrderMutationPathParams,
		Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function deleteOrder(props: DeleteOrderProps): Promise<DeleteOrderOkResponse> {
	return fetcher<DeleteOrderOkResponse, unknown, unknown>({
		url: `/store/order/${props.orderId}`,
		method: 'DELETE',
		...props,
	});
}

/**
 * For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
 */
export function useDeleteOrderMutation(
	props: DeleteOrderProps,
	options?: Omit<
		UseMutationOptions<DeleteOrderOkResponse, DeleteOrderErrorResponse>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<DeleteOrderOkResponse, DeleteOrderErrorResponse>(
		() => deleteOrder(props),
		options,
	);
}
