/* This is a sample header */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useQuery, UseQueryOptions } from '@tanstack/react-query';

import type { Pet } from '../schemas/Pet';
import { fetcher, FetcherOptions } from './fetcher';

export interface UseGetPetByIdQueryPathParams {
	/**
	 * @format int64
	 */
	petId: number;
}

export type GetPetByIdOkResponse = Pet;

export type GetPetByIdErrorResponse = unknown;

export interface GetPetByIdProps
	extends UseGetPetByIdQueryPathParams,
		Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function getPetById(props: GetPetByIdProps): Promise<GetPetByIdOkResponse> {
	const { petId, ...rest } = props;

	return fetcher<GetPetByIdOkResponse, unknown, unknown>({
		url: `/pet/${petId}`,
		method: 'GET',
		...rest,
	});
}

/**
 * Returns a single pet
 */
export function useGetPetByIdQuery(
	props: GetPetByIdProps,
	options?: Omit<
		UseQueryOptions<GetPetByIdOkResponse, GetPetByIdErrorResponse>,
		'queryKey' | 'queryFn'
	>,
) {
	return useQuery<GetPetByIdOkResponse, GetPetByIdErrorResponse>(
		['getPetById'],
		({ signal }) => getPetById({ ...props, signal }),
		options,
	);
}
