/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useQuery, UseQueryOptions } from '@tanstack/react-query';

import type { Pet } from '../schemas/Pet';
import { fetcher, FetcherOptions } from './fetcher';

export interface UseGetPetByIdQueryPathParams {
	/**
	 * @format int64
	 */
	petId: number;
}

export type GetPetByIdResponse = Pet;

export type GetPetByIdError = unknown;

export interface GetPetByIdProps
	extends UseGetPetByIdQueryPathParams,
		Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function getPetById(props: GetPetByIdProps): Promise<GetPetByIdResponse> {
	const { petId, ...rest } = props;

	return fetcher<GetPetByIdResponse, unknown, unknown>({
		url: `/pet/${petId}`,
		method: 'GET',
		...rest,
	});
}

/**
 * Returns a single pet
 */
export function useGetPetByIdQuery(
	props: GetPetByIdProps,
	options: Omit<UseQueryOptions<GetPetByIdResponse, GetPetByIdError>, 'queryKey' | 'queryFn'>,
) {
	return useQuery<GetPetByIdResponse, GetPetByIdError>(
		['getPetById'],
		({ signal }) => getPetById({ ...props, signal }),
		options,
	);
}
