/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useQuery, UseQueryOptions } from '@tanstack/react-query';

import { fetcher, FetcherOptions } from './fetcher';

export interface UseLoginUserQueryQueryParams {
	username: string;
	password: string;
}

export type LoginUserResponse = string;

export type LoginUserError = unknown;

export interface LoginUserProps
	extends Omit<FetcherOptions<UseLoginUserQueryQueryParams, unknown>, 'url'> {
	queryParams: UseLoginUserQueryQueryParams;
}

export function loginUser(props: LoginUserProps): Promise<LoginUserResponse> {
	const { ...rest } = props;

	return fetcher<LoginUserResponse, UseLoginUserQueryQueryParams, unknown>({
		url: `/user/login`,
		method: 'GET',
		...rest,
	});
}

/**
 *
 */
export function useLoginUserQuery(
	props: LoginUserProps,
	options: Omit<UseQueryOptions<LoginUserResponse, LoginUserError>, 'queryKey' | 'queryFn'>,
) {
	return useQuery<LoginUserResponse, LoginUserError>(
		['loginUser'],
		({ signal }) => loginUser({ ...props, signal }),
		options,
	);
}
