/* This is a sample header */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { User } from '../schemas/User';
import { fetcher, FetcherOptions } from './fetcher';

export interface UpdateUserMutationPathParams {
	username: string;
}

export type UpdateUserRequestBody = User;

export type UpdateUserOkResponse = unknown;

export type UpdateUserErrorResponse = unknown;

export interface UpdateUserProps
	extends UpdateUserMutationPathParams,
		Omit<FetcherOptions<unknown, UpdateUserRequestBody>, 'url'> {
	body: UpdateUserRequestBody;
}

export function updateUser(props: UpdateUserProps): Promise<UpdateUserOkResponse> {
	return fetcher<UpdateUserOkResponse, unknown, UpdateUserRequestBody>({
		url: `/user/${props.username}`,
		method: 'PUT',
		...props,
	});
}

/**
 * This can only be done by the logged in user.
 */
export function useUpdateUserMutation(
	props: UpdateUserProps,
	options?: Omit<
		UseMutationOptions<UpdateUserOkResponse, UpdateUserErrorResponse>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<UpdateUserOkResponse, UpdateUserErrorResponse>(
		() => updateUser(props),
		options,
	);
}
