/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import { fetcher, FetcherOptions } from './fetcher';

export interface UseUpdatePetWithFormMutationPathParams {
	/**
	 * @format int64
	 */
	petId: number;
}

export type UpdatePetWithFormRequestBody = unknown;

export type UpdatePetWithFormOkResponse = unknown;

export type UpdatePetWithFormErrorResponse = unknown;

export interface UpdatePetWithFormProps
	extends UseUpdatePetWithFormMutationPathParams,
		Omit<FetcherOptions<unknown, UpdatePetWithFormRequestBody>, 'url'> {
	body: UpdatePetWithFormRequestBody;
}

export function updatePetWithForm(
	props: UpdatePetWithFormProps,
): Promise<UpdatePetWithFormOkResponse> {
	const { petId, ...rest } = props;

	return fetcher<UpdatePetWithFormOkResponse, unknown, UpdatePetWithFormRequestBody>({
		url: `/pet/${petId}`,
		method: 'POST',
		...rest,
	});
}

/**
 *
 */
export function useUpdatePetWithFormMutation(
	props: UpdatePetWithFormProps,
	options: Omit<
		UseMutationOptions<UpdatePetWithFormOkResponse, UpdatePetWithFormErrorResponse>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<UpdatePetWithFormOkResponse, UpdatePetWithFormErrorResponse>(
		() => updatePetWithForm(props),
		options,
	);
}
