/* This is a sample header */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { ApiResponse } from '../schemas/ApiResponse';
import { fetcher, FetcherOptions } from './fetcher';

export interface UseUploadFileMutationPathParams {
	/**
	 * @format int64
	 */
	petId: number;
}

export type UploadFileRequestBody = unknown;

export type UploadFileOkResponse = ApiResponse;

export type UploadFileErrorResponse = unknown;

export interface UploadFileProps
	extends UseUploadFileMutationPathParams,
		Omit<FetcherOptions<unknown, UploadFileRequestBody>, 'url'> {
	body: UploadFileRequestBody;
}

export function uploadFile(props: UploadFileProps): Promise<UploadFileOkResponse> {
	const { petId, ...rest } = props;

	return fetcher<UploadFileOkResponse, unknown, UploadFileRequestBody>({
		url: `/pet/${petId}/uploadImage`,
		method: 'POST',
		...rest,
	});
}

/**
 *
 */
export function useUploadFileMutation(
	props: UploadFileProps,
	options?: Omit<
		UseMutationOptions<UploadFileOkResponse, UploadFileErrorResponse>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<UploadFileOkResponse, UploadFileErrorResponse>(
		() => uploadFile(props),
		options,
	);
}
