/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.
import type { ServicesV2YamlMetadataDto } from '../schemas/ServicesV2YamlMetadataDto';

export interface ResponseServicesV2YamlMetadataDto {
	correlationId?: string;
	data?: ServicesV2YamlMetadataDto;
	metaData?: unknown;
	status?: 'ERROR' | 'FAILURE' | 'SUCCESS';
}
