/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.
import type { ServiceResponse } from '../schemas/ServiceResponse';

export interface ResponseListServiceResponse {
	correlationId?: string;
	data?: ServiceResponse[];
	metaData?: unknown;
	status?: 'ERROR' | 'FAILURE' | 'SUCCESS';
}
