/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.
import type { ServiceResponseDto } from '../schemas/ServiceResponseDto';

export interface ServiceResponse {
	/**
	 * @format int64
	 */
	createdAt?: number;
	/**
	 * @format int64
	 */
	lastModifiedAt?: number;
	service?: ServiceResponseDto;
}
