/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.

export interface ServiceResponseDto {
	accountId?: string;
	deleted?: boolean;
	description?: string;
	identifier?: string;
	name?: string;
	orgIdentifier?: string;
	projectIdentifier?: string;
	tags?: unknown;
	yaml?: string;
}
