/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.
import type { ServiceV2YamlMetadata } from '../schemas/ServiceV2YamlMetadata';

export interface ServicesV2YamlMetadataDto {
	serviceV2YamlMetadataList?: ServiceV2YamlMetadata[];
}
