/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.

export interface ServicesYamlMetadataApiInput {
	serviceIdentifiers: string[];
}
