/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.

export interface ServiceV2YamlMetadata {
	inputSetTemplateYaml?: string;
	serviceIdentifier: string;
	serviceYaml?: string;
}
