/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.

export interface StackTraceElement {
	classLoaderName?: string;
	className?: string;
	fileName?: string;
	/**
	 * @format int32
	 */
	lineNumber?: number;
	methodName?: string;
	moduleName?: string;
	moduleVersion?: string;
	nativeMethod?: boolean;
}
