/* This is a sample header */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.

export interface ApiResponse {
	/**
	 * @format int32
	 */
	code?: number;
	message?: string;
	type?: string;
}
