/* This is a sample header */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.

export interface Category {
	/**
	 * @format int64
	 */
	id?: number;
	name?: string;
}
