/* This is a sample header */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.

export interface User {
	email?: string;
	firstName?: string;
	/**
	 * @format int64
	 */
	id?: number;
	lastName?: string;
	password?: string;
	phone?: string;
	/**
	 * User Status
	 * @format int32
	 */
	userStatus?: number;
	username?: string;
}
