/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.
import type { Pet } from '../schemas/Pet';

export type PetRequestBody = Pet;
