/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

/**
 * Basic Error
 */

export interface BasicError {
	documentation_url?: string;
	message?: string;
	status?: string;
	url?: string;
}
