/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

/**
 * License Simple
 */

export type NullableLicenseSimple = unknown | null;
