/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

/**
 * Validation Error
 */

export interface ValidationError {
	documentation_url: string;
	errors?: unknown[];
	message: string;
}
