/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

/**
 * Validation Error
 */

export interface ValidationError {
	documentation_url: string;
	errors?: Array<{
		code: string;
		field?: string;
		index?: number;
		message?: string;
		resource?: string;
		value?: string | (null & number) | (null & string[]) | null;
	}>;
	message: string;
}
