/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { Pet } from '../schemas/Pet';
import { fetcher, FetcherOptions } from './fetcher';

export type AddPetResponse = Pet;

export type AddPetError = unknown;

export interface AddPetProps extends Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function addPet(props: AddPetProps): Promise<AddPetResponse> {
	const { ...rest } = props;

	return fetcher<AddPetResponse, unknown, unknown>({
		url: `/pet`,
		method: 'POST',
		...rest,
	});
}

/**
 * Add a new pet to the store
 */
export function useAddPetMutation(
	props: AddPetProps,
	options: Omit<UseMutationOptions<AddPetResponse, AddPetError>, 'mutationKey' | 'mutationFn'>,
) {
	return useMutation<AddPetResponse, AddPetError>(() => addPet(props), options);
}
