/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { User } from '../schemas/User';
import { fetcher, FetcherOptions } from './fetcher';

export type CreateUsersWithListInputResponse = User;

export type CreateUsersWithListInputError = unknown;

export interface CreateUsersWithListInputProps
	extends Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function createUsersWithListInput(
	props: CreateUsersWithListInputProps,
): Promise<CreateUsersWithListInputResponse> {
	const { ...rest } = props;

	return fetcher<CreateUsersWithListInputResponse, unknown, unknown>({
		url: `/user/createWithList`,
		method: 'POST',
		...rest,
	});
}

/**
 * Creates list of users with given input array
 */
export function useCreateUsersWithListInputMutation(
	props: CreateUsersWithListInputProps,
	options: Omit<
		UseMutationOptions<CreateUsersWithListInputResponse, CreateUsersWithListInputError>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<CreateUsersWithListInputResponse, CreateUsersWithListInputError>(
		() => createUsersWithListInput(props),
		options,
	);
}
