/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { User } from '../schemas/User';
import { fetcher, FetcherOptions } from './fetcher';

export type CreateUsersWithListInputRequestBody = User[];

export type CreateUsersWithListInputOkResponse = User;

export type CreateUsersWithListInputErrorResponse = unknown;

export interface CreateUsersWithListInputProps
	extends Omit<FetcherOptions<unknown, CreateUsersWithListInputRequestBody>, 'url'> {
	body: CreateUsersWithListInputRequestBody;
}

export interface CreateUsersWithListInputResponseContainer {
	content: CreateUsersWithListInputOkResponse;
	headers: HeadersInit;
}

export function createUsersWithListInput(
	props: CreateUsersWithListInputProps,
): Promise<CreateUsersWithListInputResponseContainer> {
	return fetcher<CreateUsersWithListInputOkResponse, unknown, CreateUsersWithListInputRequestBody>({
		url: `/user/createWithList`,
		method: 'POST',
		...props,
	});
}

export type CreateUsersWithListInputMutationProps<T extends keyof CreateUsersWithListInputProps> =
	Omit<CreateUsersWithListInputProps, T> & Partial<Pick<CreateUsersWithListInputProps, T>>;

/**
 * Creates list of users with given input array
 */
export function useCreateUsersWithListInputMutation<T extends keyof CreateUsersWithListInputProps>(
	props: Pick<Partial<CreateUsersWithListInputProps>, T>,
	options?: Omit<
		UseMutationOptions<
			CreateUsersWithListInputResponseContainer,
			CreateUsersWithListInputErrorResponse,
			CreateUsersWithListInputMutationProps<T>
		>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<
		CreateUsersWithListInputResponseContainer,
		CreateUsersWithListInputErrorResponse,
		CreateUsersWithListInputMutationProps<T>
	>(
		(mutateProps: CreateUsersWithListInputMutationProps<T>) =>
			createUsersWithListInput({ ...props, ...mutateProps } as CreateUsersWithListInputProps),
		options,
	);
}
