/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import { fetcher, FetcherOptions } from './fetcher';

export interface UseDeletePetMutationPathParams {
	/**
	 * @format int64
	 */
	petId: number;
}

export type DeletePetResponse = unknown;

export type DeletePetError = unknown;

export interface DeletePetProps
	extends UseDeletePetMutationPathParams,
		Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function deletePet(props: DeletePetProps): Promise<DeletePetResponse> {
	const { petId, ...rest } = props;

	return fetcher<DeletePetResponse, unknown, unknown>({
		url: `/pet/${petId}`,
		method: 'DELETE',
		...rest,
	});
}

/**
 *
 */
export function useDeletePetMutation(
	props: DeletePetProps,
	options: Omit<
		UseMutationOptions<DeletePetResponse, DeletePetError>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<DeletePetResponse, DeletePetError>(() => deletePet(props), options);
}
