/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import { fetcher, FetcherOptions } from './fetcher';

export interface DeleteOrderMutationPathParams {
	/**
	 * @format int64
	 */
	orderId: number;
}

export type DeleteOrderOkResponse = unknown;

export type DeleteOrderErrorResponse = unknown;

export interface DeleteOrderProps
	extends DeleteOrderMutationPathParams,
		Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function deleteOrder(props: DeleteOrderProps): Promise<DeleteOrderOkResponse> {
	const { orderId, ...rest } = props;

	return fetcher<DeleteOrderOkResponse, unknown, unknown>({
		url: `/store/order/${orderId}`,
		method: 'DELETE',
		...rest,
	});
}

/**
 * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
 */
export function useDeleteOrderMutation(
	props: DeleteOrderProps,
	options?: Omit<
		UseMutationOptions<DeleteOrderOkResponse, DeleteOrderErrorResponse>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<DeleteOrderOkResponse, DeleteOrderErrorResponse>(
		() => deleteOrder(props),
		options,
	);
}
