/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useQuery, UseQueryOptions } from '@tanstack/react-query';

import type { Pet } from '../schemas/Pet';
import { fetcher, FetcherOptions } from './fetcher';

export interface UseFindPetsByStatusQueryQueryParams {
	/**
	 * @default "available"
	 */
	status?: 'available' | 'pending' | 'sold';
}

export type FindPetsByStatusResponse = Pet[];

export type FindPetsByStatusError = unknown;

export interface FindPetsByStatusProps
	extends Omit<FetcherOptions<UseFindPetsByStatusQueryQueryParams, unknown>, 'url'> {
	queryParams: UseFindPetsByStatusQueryQueryParams;
}

export function findPetsByStatus(props: FindPetsByStatusProps): Promise<FindPetsByStatusResponse> {
	const { ...rest } = props;

	return fetcher<FindPetsByStatusResponse, UseFindPetsByStatusQueryQueryParams, unknown>({
		url: `/pet/findByStatus`,
		method: 'GET',
		...rest,
	});
}

/**
 * Multiple status values can be provided with comma separated strings
 */
export function useFindPetsByStatusQuery(
	props: FindPetsByStatusProps,
	options: Omit<
		UseQueryOptions<FindPetsByStatusResponse, FindPetsByStatusError>,
		'queryKey' | 'queryFn'
	>,
) {
	return useQuery<FindPetsByStatusResponse, FindPetsByStatusError>(
		['findPetsByStatus'],
		({ signal }) => findPetsByStatus({ ...props, signal }),
		options,
	);
}
