/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useQuery, UseQueryOptions } from '@tanstack/react-query';

import type { Order } from '../schemas/Order';
import { fetcher, FetcherOptions } from './fetcher';

export interface UseGetOrderByIdQueryPathParams {
	/**
	 * @format int64
	 */
	orderId: number;
}

export type GetOrderByIdOkResponse = Order;

export type GetOrderByIdErrorResponse = unknown;

export interface GetOrderByIdProps
	extends UseGetOrderByIdQueryPathParams,
		Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function getOrderById(props: GetOrderByIdProps): Promise<GetOrderByIdOkResponse> {
	const { orderId, ...rest } = props;

	return fetcher<GetOrderByIdOkResponse, unknown, unknown>({
		url: `/store/order/${orderId}`,
		method: 'GET',
		...rest,
	});
}

/**
 * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
 */
export function useGetOrderByIdQuery(
	props: GetOrderByIdProps,
	options: Omit<
		UseQueryOptions<GetOrderByIdOkResponse, GetOrderByIdErrorResponse>,
		'queryKey' | 'queryFn'
	>,
) {
	return useQuery<GetOrderByIdOkResponse, GetOrderByIdErrorResponse>(
		['getOrderById'],
		({ signal }) => getOrderById({ ...props, signal }),
		options,
	);
}
