/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useQuery, UseQueryOptions } from '@tanstack/react-query';

import { fetcher, FetcherOptions } from './fetcher';

export type GetInventoryResponse = { '[key: string]'?: number };

export type GetInventoryError = unknown;

export interface GetInventoryProps extends Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function getInventory(props: GetInventoryProps): Promise<GetInventoryResponse> {
	const { ...rest } = props;

	return fetcher<GetInventoryResponse, unknown, unknown>({
		url: `/store/inventory`,
		method: 'GET',
		...rest,
	});
}

/**
 * Returns a map of status codes to quantities
 */
export function useGetInventoryQuery(
	props: GetInventoryProps,
	options: Omit<UseQueryOptions<GetInventoryResponse, GetInventoryError>, 'queryKey' | 'queryFn'>,
) {
	return useQuery<GetInventoryResponse, GetInventoryError>(
		['getInventory'],
		({ signal }) => getInventory({ ...props, signal }),
		options,
	);
}
