/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.
import { useQuery, UseQueryOptions } from '@tanstack/react-query';

import { fetcher, FetcherOptions } from './fetcher';

export type GetInventoryOkResponse = unknown;

export type GetInventoryErrorResponse = unknown;

export interface GetInventoryProps extends Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function getInventory(props: GetInventoryProps): Promise<GetInventoryOkResponse> {
	const { ...rest } = props;

	return fetcher<GetInventoryOkResponse, unknown, unknown>({
		url: `/store/inventory`,
		method: 'GET',
		...rest,
	});
}

/**
 * Returns a map of status codes to quantities
 */
export function useGetInventoryQuery(
	props: GetInventoryProps,
	options?: Omit<
		UseQueryOptions<GetInventoryOkResponse, GetInventoryErrorResponse>,
		'queryKey' | 'queryFn'
	>,
) {
	return useQuery<GetInventoryOkResponse, GetInventoryErrorResponse>(
		['getInventory'],
		({ signal }) => getInventory({ ...props, signal }),
		options,
	);
}
