/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useQuery, UseQueryOptions } from '@tanstack/react-query';

import { fetcher, FetcherOptions } from './fetcher';

export type LogoutUserResponse = unknown;

export type LogoutUserError = unknown;

export interface LogoutUserProps extends Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function logoutUser(props: LogoutUserProps): Promise<LogoutUserResponse> {
	const { ...rest } = props;

	return fetcher<LogoutUserResponse, unknown, unknown>({
		url: `/user/logout`,
		method: 'GET',
		...rest,
	});
}

/**
 *
 */
export function useLogoutUserQuery(
	props: LogoutUserProps,
	options: Omit<UseQueryOptions<LogoutUserResponse, LogoutUserError>, 'queryKey' | 'queryFn'>,
) {
	return useQuery<LogoutUserResponse, LogoutUserError>(
		['logoutUser'],
		({ signal }) => logoutUser({ ...props, signal }),
		options,
	);
}
