/* eslint-disable */
// This code is autogenerated using @harnessio/oats CLI.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { Order } from '../schemas/Order';
import { fetcher, FetcherOptions } from './fetcher';

export type PlaceOrderRequestBody = Order;

export type PlaceOrderOkResponse = Order;

export type PlaceOrderErrorResponse = unknown;

export interface PlaceOrderProps
	extends Omit<FetcherOptions<unknown, PlaceOrderRequestBody>, 'url'> {
	body: PlaceOrderRequestBody;
}

export function placeOrder(props: PlaceOrderProps): Promise<PlaceOrderOkResponse> {
	const { ...rest } = props;

	return fetcher<PlaceOrderOkResponse, unknown, PlaceOrderRequestBody>({
		url: `/store/order`,
		method: 'POST',
		...rest,
	});
}

/**
 * Place a new order in the store
 */
export function usePlaceOrderMutation(
	props: PlaceOrderProps,
	options?: Omit<
		UseMutationOptions<PlaceOrderOkResponse, PlaceOrderErrorResponse>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<PlaceOrderOkResponse, PlaceOrderErrorResponse>(
		() => placeOrder(props),
		options,
	);
}
