/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { Order } from '../schemas/Order';
import { fetcher, FetcherOptions } from './fetcher';

export type PlaceOrderResponse = Order;

export type PlaceOrderError = unknown;

export interface PlaceOrderProps extends Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function placeOrder(props: PlaceOrderProps): Promise<PlaceOrderResponse> {
	const { ...rest } = props;

	return fetcher<PlaceOrderResponse, unknown, unknown>({
		url: `/store/order`,
		method: 'POST',
		...rest,
	});
}

/**
 * Place a new order in the store
 */
export function usePlaceOrderMutation(
	props: PlaceOrderProps,
	options: Omit<
		UseMutationOptions<PlaceOrderResponse, PlaceOrderError>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<PlaceOrderResponse, PlaceOrderError>(() => placeOrder(props), options);
}
