/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { Pet } from '../schemas/Pet';
import { fetcher, FetcherOptions } from './fetcher';

export type UpdatePetRequestBody = Pet;

export type UpdatePetOkResponse = Pet;

export type UpdatePetErrorResponse = unknown;

export interface UpdatePetProps extends Omit<FetcherOptions<unknown, UpdatePetRequestBody>, 'url'> {
	body: UpdatePetRequestBody;
}

export interface UpdatePetResponseContainer {
	content: UpdatePetOkResponse;
	headers: HeadersInit;
}

export function updatePet(props: UpdatePetProps): Promise<UpdatePetResponseContainer> {
	return fetcher<UpdatePetOkResponse, unknown, UpdatePetRequestBody>({
		url: `/pet`,
		method: 'PUT',
		...props,
	});
}

export type UpdatePetMutationProps<T extends keyof UpdatePetProps> = Omit<UpdatePetProps, T> &
	Partial<Pick<UpdatePetProps, T>>;

/**
 * Update an existing pet by Id
 */
export function useUpdatePetMutation<T extends keyof UpdatePetProps>(
	props: Pick<Partial<UpdatePetProps>, T>,
	options?: Omit<
		UseMutationOptions<
			UpdatePetResponseContainer,
			UpdatePetErrorResponse,
			UpdatePetMutationProps<T>
		>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<UpdatePetResponseContainer, UpdatePetErrorResponse, UpdatePetMutationProps<T>>(
		(mutateProps: UpdatePetMutationProps<T>) =>
			updatePet({ ...props, ...mutateProps } as UpdatePetProps),
		options,
	);
}
