/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { Pet } from '../schemas/Pet';
import { fetcher, FetcherOptions } from './fetcher';

export type UpdatePetResponse = Pet;

export type UpdatePetError = unknown;

export interface UpdatePetProps extends Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function updatePet(props: UpdatePetProps): Promise<UpdatePetResponse> {
	const { ...rest } = props;

	return fetcher<UpdatePetResponse, unknown, unknown>({
		url: `/pet`,
		method: 'PUT',
		...rest,
	});
}

/**
 * Update an existing pet by Id
 */
export function useUpdatePetMutation(
	props: UpdatePetProps,
	options: Omit<
		UseMutationOptions<UpdatePetResponse, UpdatePetError>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<UpdatePetResponse, UpdatePetError>(() => updatePet(props), options);
}
