/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { Pet } from '../schemas/Pet';
import { fetcher, FetcherOptions } from './fetcher';

export type UpdatePetRequestBody = Pet;

export type UpdatePetOkResponse = Pet;

export type UpdatePetErrorResponse = unknown;

export interface UpdatePetProps extends Omit<FetcherOptions<unknown, UpdatePetRequestBody>, 'url'> {
	body: UpdatePetRequestBody;
}

export function updatePet(props: UpdatePetProps): Promise<UpdatePetOkResponse> {
	return fetcher<UpdatePetOkResponse, unknown, UpdatePetRequestBody>({
		url: `/pet`,
		method: 'PUT',
		...props,
	});
}

/**
 * Update an existing pet by Id
 */
export function useUpdatePetMutation(
	props: UpdatePetProps,
	options?: Omit<
		UseMutationOptions<UpdatePetOkResponse, UpdatePetErrorResponse>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<UpdatePetOkResponse, UpdatePetErrorResponse>(() => updatePet(props), options);
}
