/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { User } from '../schemas/User';
import { fetcher, FetcherOptions } from './fetcher';

export interface UseUpdateUserMutationPathParams {
	username: string;
}

export type UpdateUserResponse = unknown;

export type UpdateUserError = unknown;

export interface UpdateUserProps
	extends UseUpdateUserMutationPathParams,
		Omit<FetcherOptions<unknown, unknown>, 'url'> {}

export function updateUser(props: UpdateUserProps): Promise<UpdateUserResponse> {
	const { username, ...rest } = props;

	return fetcher<UpdateUserResponse, unknown, unknown>({
		url: `/user/${username}`,
		method: 'PUT',
		...rest,
	});
}

/**
 * This can only be done by the logged in user.
 */
export function useUpdateUserMutation(
	props: UpdateUserProps,
	options: Omit<
		UseMutationOptions<UpdateUserResponse, UpdateUserError>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<UpdateUserResponse, UpdateUserError>(() => updateUser(props), options);
}
