/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import { fetcher, FetcherOptions } from './fetcher';

export interface UpdatePetWithFormMutationPathParams {
	/**
	 * @format int64
	 */
	petId: number;
}

export interface UpdatePetWithFormMutationQueryParams {
	name?: string;
	status?: string;
}

export type UpdatePetWithFormOkResponse = unknown;

export type UpdatePetWithFormErrorResponse = unknown;

export interface UpdatePetWithFormProps
	extends UpdatePetWithFormMutationPathParams,
		Omit<FetcherOptions<UpdatePetWithFormMutationQueryParams, unknown>, 'url'> {
	queryParams: UpdatePetWithFormMutationQueryParams;
}

export function updatePetWithForm(
	props: UpdatePetWithFormProps,
): Promise<UpdatePetWithFormOkResponse> {
	return fetcher<UpdatePetWithFormOkResponse, UpdatePetWithFormMutationQueryParams, unknown>({
		url: `/pet/${props.petId}`,
		method: 'POST',
		...props,
	});
}

/**
 *
 */
export function useUpdatePetWithFormMutation(
	props: UpdatePetWithFormProps,
	options?: Omit<
		UseMutationOptions<UpdatePetWithFormOkResponse, UpdatePetWithFormErrorResponse>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<UpdatePetWithFormOkResponse, UpdatePetWithFormErrorResponse>(
		() => updatePetWithForm(props),
		options,
	);
}
