/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import { fetcher, FetcherOptions } from './fetcher';

export interface UseUpdatePetWithFormMutationPathParams {
	/**
	 * @format int64
	 */
	petId: number;
}

export interface UseUpdatePetWithFormMutationQueryParams {
	name?: string;
	status?: string;
}

export type UpdatePetWithFormResponse = unknown;

export type UpdatePetWithFormError = unknown;

export interface UpdatePetWithFormProps
	extends UseUpdatePetWithFormMutationPathParams,
		Omit<FetcherOptions<UseUpdatePetWithFormMutationQueryParams, unknown>, 'url'> {
	queryParams: UseUpdatePetWithFormMutationQueryParams;
}

export function updatePetWithForm(
	props: UpdatePetWithFormProps,
): Promise<UpdatePetWithFormResponse> {
	const { petId, ...rest } = props;

	return fetcher<UpdatePetWithFormResponse, UseUpdatePetWithFormMutationQueryParams, unknown>({
		url: `/pet/${petId}`,
		method: 'POST',
		...rest,
	});
}

/**
 *
 */
export function useUpdatePetWithFormMutation(
	props: UpdatePetWithFormProps,
	options: Omit<
		UseMutationOptions<UpdatePetWithFormResponse, UpdatePetWithFormError>,
		'mutationKey' | 'mutationFn'
	>,
) {
	return useMutation<UpdatePetWithFormResponse, UpdatePetWithFormError>(
		() => updatePetWithForm(props),
		options,
	);
}
