/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface Address {
	/**
	 * @example "Palo Alto"
	 */
	city?: string;
	/**
	 * @example "CA"
	 */
	state?: string;
	/**
	 * @example "437 Lytton"
	 */
	street?: string;
	/**
	 * @example 94301
	 */
	zip?: string;
}
