/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface Category {
	/**
	 * @format int64
	 * @example 1
	 */
	id?: number;
	/**
	 * @example "Dogs"
	 */
	name?: string;
}
