/* This is a sample header */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { User } from '../schemas/User';

export type UserArrayRequestBody = User[];
